jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # important

      - name: Check .git folder exists
        run: ls -la .git

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.FTP_SCHOOLIZER_SERVER }}
          ftp-username: ${{ secrets.FTP_SCHOOLIZER_USER }}
          ftp-password: ${{ secrets.FTP_SCHOOLIZER_PASS }}
          local-dir: ./   # or ./schoolizer if code is in subfolder
          server-dir: public_html/schoolizer/