name: Publish Website to CPanel

on:
  push:
    branches:
      - prod

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Deploy via FTP to cPanel
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.FTP_SCHOOLIZER_SERVER }}
          ftp-username: ${{ secrets.FTP_SCHOOLIZER_USER }}
          ftp-password: ${{ secrets.FTP_SCHOOLIZER_PASS }}
          local-dir: ./
          git-ftp-args: --remote-root public_html/schoolizer --force
