name: Publish Website to CPanel

on:
  push:
    branches:
      - prod

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy via FTP to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SCHOOLIZER_SERVER }}
          username: ${{ secrets.FTP_SCHOOLIZER_USER }}
          password: ${{ secrets.FTP_SCHOOLIZER_PASS }}
          local-dir: ./
          server-dir: ./
