name: Publish Website to CPanel

on:
  push:
    branches:
      - prod   # Deploys only when you push/merge to prod branch

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout full git repo (important for git-ftp)
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0   # Fetch full history, not shallow clone

      # Optional: Debug to verify .git folder exists
      - name: Verify .git folder exists
        run: ls -la .git

      # Step 2: Deploy using SamKirkland FTP-Deploy-Action
      - name: Deploy via FTP to cPanel
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.FTP_SCHOOLIZER_SERVER }}
          ftp-username: ${{ secrets.FTP_SCHOOLIZER_USER }}
          ftp-password: ${{ secrets.FTP_SCHOOLIZER_PASS }}
          local-dir: ./              # Your local project folder, change if needed
          git-ftp-args: --remote-root public_html/schoolizer  # Upload to this folder on server
